source/taunt_toggles.h, source/training/common.hpp, source/training/mash.hpp, source/training/shield.hpp
Mash options will now be performed when the CPU shield is hit.
Supported OOS options are aerial attacks, grab, up b, up smash and spotdodge.
The code should be revised as I don't know if some of the things I added should go in other files maybe.
=> Added Out Of Shield Mash Options

README.md, src/training/mod.rs, src/training/shield.rs
Shield decay is paused until hit for the first time to simulate a frame perfect shield hold
=> Update Hold Shield Mode

README.md, src/common/consts.rs, src/common/mod.rs, src/hitbox_visualizer/mod.rs, src/training/mash.rs, src/training/shield.rs
- Added toggle to set the cpu to also mash in neutral
Grab + dpad Left => start mashing
Grab + dpad Right => stop mashing
- Added utility functions in common::mod
1. is_grounded
2. is_airborne
=> Add Neutral Mashing Toggle

src/common/consts.rs, src/common/mod.rs, src/training/directional_influence.rs, src/training/left_stick.rs, src/training/mash.rs, src/training/mod.rs
- Added option for directional air dodges
- Renamed DirectionalInfluence enum to Direction
- Moved angle calculation to common
- Renamed NO_DI to ANGLE_NONE and moved to common
- Fixed a bug where the CPU would always flash shield when Mash::AirDodge is set
=> Add Directional Air Dodge

TrainingModpackOverlay/include/taunt_toggles.hpp, src/common/consts.rs, src/common/mod.rs, src/training/directional_influence.rs, src/training/ledge.rs, src/training/left_stick.rs, src/training/mash.rs, src/training/tech.rs
Also  added wrapper for rand() call
Overlay PR:
https://github.com/jugeeya/TrainingModpackOverlay/pull/20
=> Separate Tech Rolls

src/training/mash.rs
Revert 4cc6654 => was causing NAir, unless a followup was selected
Removed shield::is_aerial check => Non Aerials will just return None in into_attack_air_kind()
=> Fix Aerials

TrainingModpackOverlay/include/taunt_toggles.hpp, src/common/consts.rs, src/training/mash.rs
Known Issues:
Mash is not reset automatically for dash attack
Dash Attack skips the first dashing frame
=> Enable Dash Attack Again

TrainingModpackOverlay/include/taunt_toggles.hpp, src/common/consts.rs, src/lib.rs, src/training/ledge.rs, src/training/mod.rs
Fixes issue #88.
Adds a "Wait" option to the ledge options submenu. When this option is selected, the CPU will not take any ledge action and will hold on to ledge until it is knocked off or reaches the ledge timer.
=> Ledge hang

src/common/consts.rs, src/training/air_dodge_direction.rs, src/training/directional_influence.rs, src/training/sdi.rs
Resolves #205 and #181
DI is only rolled on the first frame of hitstun, preventing the indicator from wiggling as new DI directions are selected
Adds a left and right option to the Direction struct used in DI/SDI/Airdodge settings. The should_reverse_angle function now takes the Direction as an argument and uses that in its logic.
=> DI Indicator Fix and Left/Right Directions

src/training/ledge.rs
* Only apply ledge::is_enable_transition_term to CPU
=> Fix a bug where the Player was prevented from performing neutral getup

src/common/mod.rs, src/common/release.rs, src/lib.rs
This PR implements the following:
- Upon loading the modpack, display a dialog box with information about the new button combination if the software detects an upgrade or a fresh installation
- Most recent version information is stored in sd:/TrainingModpack/version.txt, which is compared to the current version to determine upgrade status
- Afterwards, write the current package version to version.txt so that the dialog box will not be displayed again
- If the Tesla overlay for the training modpack exists from a previous version, it is removed
=> Instructions for Version Update from v2.6

src/common/consts.rs, src/common/menu.rs, src/common/mod.rs, src/templates/menu.html
This PR includes the following:
- Create a static DEFAULT_MENU struct with initial values and populate the MENU by cloning that
- Add a default field to menu component structs in menu.rs which specifies what the proper reset value is
- Add HTML attribute "default=is-appear" or "default=is-hidden" to menu setting elements
- Add JS functions which set the is-appear or is-hidden classes according to the defaults. Pressing X only resets open/focused submenus, and pressing L resets all submenus after a confirmation dialog
- Add reset button descriptions to the menu header
=> Add ability to reset menus to the default

src/templates/menu.html
This PR modifies the menu Javascript to use jQuery for class addition/removal. Fixes a bug where the default would get overriden during a reset instead of the class, and homogenizes the class handling.
=> Use jQuery to handle class addition/removal

src/common/menu.rs, src/templates/menu.html
- Add a footer to the menu
- Set footer text to be the help text when a submenu is focused
- Add extra margin to the last menu element to avoid scrolling issues with the footer
- Include help text in the Submenu struct
- Write help text for all submenus
=> Menu help text

src/common/menu.rs, src/training/mod.rs
This PR implements a frame counter for the menu, which prevents opening the menu within 5 frames of the last menu open. This has the aim of preventing the annoying bug where closing the menu with B can cause it to immediately reopen.
=> Restrict menu opening multiple times in rapid succession

.github/workflows/rust.yml
Latest outside_training_mode NRO doesn't seem to function any differently than the normal NRO file. Everything works as intended inside training mode, but outside of it e.g. Smash mode, nothing works (no hitboxes) and I'm also unable to open the menu.
I believe you just need to add back in "--features outside_training_mode" when you're building the outside_training_mode NRO and it should work as intended.
=> Fix outside_training_mode NRO

src/common/mod.rs
The function is_in_hitstun() used an inclusive range operator to include FIGHTER_STATUS_KIND_DAMAGE (grounded hitstun), FIGHTER_STATUS_KIND_DAMAGE_AIR (aerial hitstun) and FIGHTER_STATUS_KIND_DAMAGE_FALL (tumble). Tumble should not be considered to be a "hitstun" state.
Note that in combo.rs, the was_in_hitstun() function already includes this change, so this PR brings those two functions into alignment, and the functionality matches the function name.
The in-game impact of this change will be allowing different DI directions to be selected during untrue combos. Shouldn't affect mash.rs or air_dodge_direction.rs since those actions are actually selected during hitstun itself.
=> Remove tumble from statuses on is_in_hitstun

src/training/tech.rs
Lets the CPU perform mistech options when laying down or slipped (snake downthrow and diddy banana respectively).
Addresses #125
=> Slip options

README.md, src/common/menu.rs, src/common/mod.rs, src/lib.rs, src/templates/menu.html, src/training/mod.rs
Allows the user to save the current menu as the new defaults, which are used when resetting the menu selections with L or with X.
The defaults are also saved in a config file to enable persistence when the game is closed.
The button combination to save the defaults is SPECIAL+JUMP+DOWNTAUNT.
Closes #279
=> Configurable default menu

src/common/mod.rs, src/training/save_states.rs
Resolves issues with save states for Pokemon Trainer. When loading a save state, the fighter now correctly sets the position/damage and cycles back to the pokemon when the state was saved. Resolves #261 
Note that when a non-PT save state (including the default state) is loaded with PT in the match (i.e. changed fighters to PT) the pokemon identity is undefined. In this case, the CPU continues to wait until it exits FIGHTER_STATUS_KIND_WAIT, then cycles to the next pokemon. Given the rarity of the situation, I'm gonna leave that as wontfix and future-me will take care of it.
=> Bugfix: PT savestates

src/common/menu.rs, src/common/mod.rs, src/training/save_states.rs
Resolves issues with save states for the Ice Climbers. When loading a save state, Nana now correctly moves to Popo, adjusts her percent to the correct amount, and maintains the functionality of her moves (she was getting killed twice like PT used to, which had glaring side effects). They would also pull up the menu twice, so the menu lockout has been increased to prevent this (and should prevent other repeat pull ups as well).
Similar to the PT fix, there are some further considerations that could be made for the Ice Climbers. Nana steals Popo's percent and position from the save state, meaning having save states with them separated or set up for a separation isn't possible. Given how relatively not useful this is, it won't be a priority for a long while. Also, because Nana receives …
=> Bugfix: Ice Climbers savestates

src/training/mod.rs, src/training/save_states.rs
Simple change to prevent the screen shake caused by player deaths when loading save states. Much smoother transition than before.
=> Smooth save state

src/training/save_states.rs
Resolves the issue where loading a save state while fighters were in hitstop would cause jostle to stay ignored until the fighters exited hitstop properly. This issue also occurred outside of save state loading, and has been fixed in those cases as well.
=> Bugfix: Save State Jostle

src/training/mod.rs
Creates inline hooks into where the training mode menu is set up to set stale moves to be on by default. Allows users to rapidly test multiple characters by simply loading the state and testing, with no need to reset the toggle every time. Also prevents users from forgetting to turn on stale moves and labbing incorrectly as a result. Deleted an empty folder and an unused comment as well.
=> Stale Moves On by default

src/training/mod.rs, src/training/save_states.rs
Fixes the issues where different death effects would play during save state loading, even though we try to hide all of them. Also silences the death sound effects when loading save states, and we now play the training mode position reset sound when resetting. Hooking these effect/sound effect functions isn't super costly, as the fighters call different ones during the game. In my testing, the only time I could see the functions I hooked being called were when fighters would die/save states were loaded.
=> Save State Loading Enhancements

src/training/charge.rs
Always removes charge flash on state load now, his handler adds it back if it's required. Fixes #318
=> remove white flash on state load

src/training/buff.rs, src/training/save_states.rs
Fixes #311, meaning the camera transitions smoothly and quickly from special zooms such as PK Thunder, Luigi's Super Jump Punch, and Jigglypuff's Rest. Works for Hero's critical smash attacks as well. Also prevents screen shake from transferring through save states, making the transition smoother in any case where a character causes quake. Additional screen shake prevention for Hero's Psyche Up buff.
=> Save State Camera Zoom and Quake Fix

src/lib.rs, src/training/sdi.rs
Changes the SDI logic to address #157. Removes the hook for smash::lua2cpp::L2CFighterCommon_FighterStatusUniqProcessDamage_hit_stop_delay and instead modifies the Vector2f argument of FighterControlModuleImpl::check_hit_stop_delay_command to set the direction of both the SDI motion and the visual indicator.
=> Fix SDI crest bug

training_mod_consts/src/lib.rs
Fixes a bug introduced by #333 where the input delay wasn't interpreted correctly.
=> bugfix for input delay

src/training/mash.rs, src/training/shield.rs
When multiple mash options are selected, shieldgrabs will no longer go through the shielddrop animation before grabbing. Fixes #241 .
=> Bugfix for shieldgrabs with multiple options selected

src/training/buff.rs
Deep Breathing causes Wii Fit Trainer to heal a small amount. This was being applied after save state damage was loaded, and so repeatedly saving and losing states would have Wii Fit Trainer become offset more and more by percent. This change makes Wii Fit always have the correct percentage from the save state.
=> Deep Breathing Buff Fix

src/common/release.rs
Removes old `.conf` files on upgrade to account for url schema changes. Displays a different dialog box for new installations than upgrades.
=> Version check for v3.3

training_mod_consts/src/lib.rs
The web menu considers all selections to have values which are powers of 2. When exporting from the menu, we call log_2 to convert from 2^X -> X. However, when passing values into the menu we didn't convert from X -> 2^X. This caused the input delay to be displayed incorrectly. Resolves #360 .
=> Fix input delay getting passed to url params incorrectly

src/training/charge.rs
Addresses #367 so fruits are thrown when charged. A simple check of "if charge_rank > 0, then pull_throw = true" doesn't work since Pac-Man will normally throw a instantly cancelled cherry charge next time he uses neutral special, and that charge has rank 0. Line endings seem to be messed up from the clippy linter fixes PR, this should set them back to our usual. If this isn't true, let me know and I'll redo the PR, but my local works well with other files' line endings, and normally doesn't have the "every line changed" issue.
=> Bonus Fruit thrown when charged

src/static/img/crouch.svg, src/training/crouch.rs, src/training/mod.rs, training_mod_consts/src/lib.rs
Adds a menu setting under the defensive tab to control CPU crouch behavior. When set to On, the CPU crouches when on the ground and not busy with other animations. When set to Off, the CPU behavior is normal.
I did try using StatusModule::change_status_request_from_script and the various FIGHTER_STATUS_KIND_SQUAT statuses but didn't find a way to make them hold the crouch. Hooking the get_stick_y function turned out to be much easier.
=> Add Crouch Setting

src/common/menu.rs, src/common/mod.rs, src/lib.rs, src/static/js/training_modpack.js, training_mod_consts/Cargo.toml, training_mod_consts/src/lib.rs, training_mod_tui/src/lib.rs, training_mod_tui/src/main.rs
This PR changes how the Web Menu receives and sends data to Rust. Previously, we were serializing the menu selections into URL query parameters, and using the initial/last URL to pass them between JS/Rust. This PR changes that serialization scheme to use JSON instead, and uses the WebSession message-passing functionality to pass them between JS/Rust.
The key advantage of this refactor is that it is more extensible and allows for more complex messages in the future, such as multiple menu presets or nested selections for followups.
The WebSession is preloaded when the user enters training mode, dramatically improving menu load times. This session is closed when the user exits training mode to avoid conflicting with other web plugins (e.g. Arcropolis). Re-starting the WebSession does cause …
=> Refactor to use Web Sessions

Cargo.toml, src/common/button_config.rs, src/common/menu.rs, src/common/mod.rs, src/common/release.rs, src/lib.rs, src/training/save_states.rs
Button configurations are now loaded from a file for opening the menu and saving/loading save states. The file is created if it doesn't exist, and will warn the user on invalid configurations (e.g. the user types "GRAV" instead of "GRAB").
=> Instead of hardcoding, load button combo configuration from a file

src/training/input_delay.rs
Fixes #389. We now grab the current controller attributes when setting input as none on input delay start up, preventing the controller state from being seen as disconnected.
=> Keep attributes for delayed input

src/common/menu.rs, src/lib.rs
Bugfix for recent betas which still attempt to use the session preloading. Now shows the loading icon again when the session is opening.
=> Don't preload session by default

src/training/mod.rs
Turns off Star KOs by hooking into the function that checks if a stage allows for Star KOs. We always return as if the current stage disallows Star KOs, so only regular blast zone kills off of the top occur.
=> No Star KOs

training_mod_consts/src/lib.rs
Some users have reported that the clatter frequency is not fast enough, so this PR speeds it up.
Separates InputFrequency into SdiFrequency and ClatterFrequency. SdiFrequency remains unchanged, but ClatterFrequency options are now one clatter input every 8, 5, or 2 frames. (from 8/6/4)
=> Make Clatter Faster

src/training/mod.rs, src/training/tech.rs
Fixes #328 
Snake's dthrow now uses a lockout timer to decide when the CPU performs the mistech option after entering the LAY_DOWN status.
=> Add a lockout timer to snake dthrow mistech options

src/common/mod.rs, src/training/clatter.rs, src/training/mod.rs
Closes #416 
When ControlModule::start_clatter() is called, grab the correct clatter step from the arguments. Then use that value when reducing the clatter time.
=> Get the correct amount to reduce clatter time from start_clatter

src/common/mod.rs
Fixes #406 
Changes the is_in_clatter() function to look at the fighter's status instead of remaining clatter time. This is necessary because the clatter time doesn't zero out after the fighter leaves the clatter status.
=> Bugfix: Clatter status check

Cargo.toml
Necessary for build to succeed on macOS
=> [Support MacOS build] Add vendored 'native-tls' as dependency

.vscode/settings.json
Applies the rust-analyzer config fix in  #439 but does not address the clippy warnings.
=> Fix rust-analyzer config

.vscode/settings.json, src/common/mod.rs, src/lib.rs, src/training/tech.rs
Instead of hooking `is_enable_passive` and setting a `static mut`, we can just call it directly instead. This is much cleaner and probably avoids issues w/ nana.
=> Refactor untechables

src/training/save_states.rs
If the fighter is Steve and the article matches the index of Steve's crafting table, we don't remove it.
=> Keep Crafting Table on state load

src/common/menu.rs, training_mod_consts/src/lib.rs
Fixed the following issues:
1. Quick menu `App` was not regenerated prior to opening the menu, so any changes made in the web menu wouldn't be reflected in the quick menu unless you also made them in the quick menu
2. Quick menu loop did not release its mutex guard
3. Single option submenus would not have their toggles `checked` if the selected option had a value of 0, which could cause those submenus to have no `checked` toggles at all
4. Quick menu closes immediately upon opening on console
=> Fix issues w/ Quick menu

src/training/save_states.rs
Fixes #275 and #407 
1. Now applies an offset in the x-direction when loading a mirrored save state on asymmetric stages (Smashville, Town & City, Yoshi's Island)
2. When creating a save state, if the fighter is on the ledge then consider them to be in the air. When loading the save state, the fighter will immediately snap to the ledge.
=> Save States: Handle Ledges and Asymmetric Stages

Cargo.toml, src/common/button_config.rs, src/common/menu.rs, src/common/release.rs, src/hazard_manager/mod.rs, src/hitbox_visualizer/mod.rs, src/lib.rs, src/logging.rs, src/training/mod.rs
This PR improves error handling by
* Converting `unwrap()` calls to `expect()` with an error message. This error message will be shown to users if the plugin panics.
* Adding a `logging.rs` module which allows devs to call `info!`, `warn!`, and `error!` to get a labeled and level-colorized output on the terminal instead of using a `println!` call
* Fixes a small bug where a panic could occur if the user is updating between versions and is missing a menu settings JSON file
=> Improve Error Handling

src/training/mod.rs, src/training/shield.rs
This updates the shield logic to use the originally loaded shield damage mul param rather than a hardcoded vanilla param that may be different than what the game (read: mods) had loaded initially.
=> update infinite shield logic

src/common/menu.rs
PR #459 exposed an error that was being silently ignored on Ryujinx when writing the web html file. That PR changed the error to be a panic, and prevents Ryujinx users from using the current version of the modpack. This PR changes the logic so that we only attempt to write this file when on console.
=> Resolve Panic on Ryujinx

.devcontainer/devcontainer.json, src/training/ui_hacks.rs
Added a UI for the slider type settings in the new ui2d quick menu.
The design for this layout can be found [here](https://www.figma.com/file/J5Paft3HxAVL0wwvODmBxW/Quick-Menu?node-id=0%3A1&t=dB2NToGEOjh1guCU-0) in the panel titled `Slider`.
As per CPU's feedback I've removed the `Min`/`Max` + `Current Min`/`Current Max` layout in favour of having just `Min`/`Max` with the values editable and capped to the `abs_min` and `abs_max` respectively.
=> Update UI for quickmenu slider values

src/common/dev_config.rs, src/common/mod.rs, src/training/mod.rs
Docstring copypaste:
> Hot-reloadable configs for quicker development
>
> In game, press L+R+A at any point to reread these configs from
> the file in sd:/TrainingModpack/dev.toml
>
> Example usage:
>
> In this file:
> ```rust
> pub struct DevConfig {
>     pub quit_menu_title: String,
>     pub quit_menu_pos_y: i32,
> }
> ```
>
> In another file such as `ui2d/menu.rs`:
> ```rust
> let dev_config = crate::dev_config::config();
> quit_menu_button.pos_y = dev_config.quit_menu_pos_y;
> quit_menu_text.as_textbox().set_text_string(&dev_config.quit_menu_title);
> ```
=> Developer TOML for hot-reloading configs

README.md, src/common/button_config.rs, src/common/dev_config.rs, src/common/menu.rs, src/common/release.rs, src/lib.rs, src/training/save_states.rs, src/training/ui/mod.rs, training_mod_consts/src/files.rs, training_mod_consts/src/lib.rs, training_mod_consts/src/options.rs
- Move files from `sd:/TrainingModpack` to `sd:/ultimate/TrainingModpack`
- Move and remove legacy path at boot if it exists
- Create `training_mod_consts/files.rs` for storing filepaths globally, migrate all existing use cases
- Small menu bug where the up press from the menu button combo counted as an input
=> Move files to sd:/ultimate/TrainingModpack

training_mod_tui/src/lib.rs
Fixed the A button handling to early out if the clicked option is already checked and the toggle's `is_single_option` flas is set to `true`
=> Bugfix: Pressing A on active option for single option toggle unchecks it

src/common/menu.rs, src/training/ui/menu.rs, src/training/ui/mod.rs, training_mod_tui/src/lib.rs, training_mod_tui/src/main.rs
GCC previously couldn't do "Previous Tab". Changing controls in menu to:
GCC:
> Previous Tab: L
> Next Tab: R
> Save Defaults: X
> Reset Current Menu Defaults: Y
> Reset All Menu Defaults: Z
ProCon:
> Previous Tab: ZL
> Next Tab: ZR
> Save Defaults: X
> Reset Current Menu Defaults: Y
> Reset All Menu Defaults: R
=> Change Menu Buttons and Help Text; HUD Off Outside Training

rust-toolchain, rust-toolchain.toml
While reading through [Overrides - The rustup book](https://rust-lang.github.io/rustup/overrides.html) I noticed we don't use the 'modern' method of specifying the channel for the Rust toolchain. This PR introduces no change to the underlying functionality.
=> Update Rust toolchain override file

src/lib.rs
Clippy is complaining about the 'once_cell' feature now being stable, so we can just remove the feature flag.
=> Fix clippy CI: once_cell is stabilized

src/common/menu.rs
Fixes #536. Lowering the threshold for the trigger press for menu navigation to be one third pressed - this is (or at least is very approximately) the amount of pressed that activates shield, so this should resolve the issue. Menu navigation also feels way better like this.
=> Lower trigger navigation threshold for plugs

src/training/input_record.rs, src/training/mash.rs
Fixes #121 where dash attacks were beginning one frame early. The dash attack mash option now properly dashes for one frame before dash attacking. Also fixes issues related to dash attacks transitioning into rolls or dash grabs when a shield mash was queued during a dash attack. Also fixes a warning from an unused variable in input recording.
=> Dash Attack Fixes

src/training/input_record.rs
Still doesn't fix weird issue I'm seeing on Ryujinx+Keyboard where flick jump is read in, but this foxes the logic at least.
=> Small fix to standby end criteria

src/common/button_config.rs, src/training/input_record.rs
Closes https://github.com/jugeeya/UltimateTrainingModpack/issues/549 . Keeping as `ATTACK+Taunt Left/right` so as to not trigger accidental pushes from save state which also uses shield+taunt.
=> Input Recording in Button Config

src/training/input_record.rs, src/training/save_states.rs, training_mod_consts/src/lib.rs, training_mod_consts/src/options.rs
Move options around. Right now we have:
Closes: https://github.com/jugeeya/UltimateTrainingModpack/issues/568
=> Input Recording Menu Refactor

.github/workflows/rust.yml, src/common/events.rs
Previous error:
```
error[E0308]: mismatched types=======> ] 190/191: training_modpack                               
--> src/common/events.rs:183:34
|
183 |         std::ffi::CStr::from_ptr(smash_version.name.as_ptr() as *const i8)
|         ------------------------ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
|         |
|         arguments to this function are incorrect
|
= note: expected raw pointer `*const u8`
found raw pointer `*const i8`
note: associated function defined here
--> /Users/austin/.cargo/skyline/toolchain/skyline/lib/rustlib/src/rust/library/core/src/ffi/c_str.rs:260:25
```
Using `ffi::c_char` directly fixes this compilation error.
=> Fix builds of modpack on M1 Mac

.github/workflows/rust.yml, Cargo.toml, README.md
- NN HID hook is now unused due to using native Smash structs
=> Remove references to NN HID hook

src/training/input_record.rs
The game would soft-freeze when loading the Quickplay lobby. This PR fixes this problem by adding a condition to check if we are in training mode before continuing to execute the code in the `set_cpu_controls()` function.
=> Fix soft-freeze on loading Quickplay lobby

src/common/release.rs, training_mod_consts/src/config.rs
Now the modpack will delete and recreate the TOML file upon a deserialization error.
=> More gracefully handle scenario when TOML file doesn't match schema

README.md, ryujinx_build.ps1
- Fix up script to start Ryujinx, ignore its logs, use cargo-skyline logs, and have the ability to CTRL+C the script to stop Ryujinx and stop logs to iterate again
- Add instructions to the README
=> Robustify Powershell script, add instructions in README

.github/workflows/rust.yml, ryujinx_build.ps1, ryujinx_build.sh
We should leave debugging symbols in our NROs so we can quickly see what function we're calling from in crash reports rather than finding the exact plugin and then finding the location in Ghidra. Just tested it, we just need to set RUSTFLAGS=-g and that's it! The binary size doesn't seem to increase too much. Tested via setting a bogus external function:
```rust
extern "C" {
#[link_name = "\u{1}blingus"]
pub fn blingus();
}
fn once_per_frame_per_fighter(
module_accessor: &mut app::BattleObjectModuleAccessor,
category: i32,
) {
if category != FIGHTER_PAD_COMMAND_CATEGORY1 {
return;
}
unsafe {
if menu::menu_condition() {
blingus();
...
```
Crash report gave: 
```
FP:                      0000000000000000
LR:                      00000008c164f2d8 (training_modpack + 0xe12d8) …
```
=> Add debug symbols into plugin NRO

ryujinx_build.ps1, src/common/button_config.rs, src/common/input.rs, src/common/menu.rs, src/lib.rs, src/training/frame_counter.rs, src/training/mod.rs, src/training/ui/menu.rs, src/training/ui/mod.rs, training_mod_consts/src/lib.rs, training_mod_tui/src/main.rs
- Add a default on toggle in order to allow users to open the menu with start press.
- Start Press for < 10 frames gives the training mod menu
- Start Hold for >= 10 frames gives the vanilla menu
- Menu Open is now either start press via the toggle above, or default B+DPad Up will always work.
- The menu opens to the button config with a long help text that explains the behavior above
- Allow users to close the menu immediately after opening it
- Closing the menu can now be done with either B or Start, and Start can close the menu even from within a submenu
- There is now a 15 frame wait after closing the menu such that inputs for closing the menu do not affect in-game (B causing a Special input, Start reopening the menu or opening the vanilla menu)
- Turn off hitbox visualization by …
=> Open Menu with Start Press

src/common/release.rs, training_mod_consts/src/config.rs
Addresses this crash
The issue was that we didn't check to see if the TRAINING_MODPACK_ROOT path before trying to write the toml config file.
=> Fix crash if the TRAINING_MODPACK_ROOT path doesn't already exist

README.md
These are the features that can be found [in the latest beta release](https://github.com/jugeeya/UltimateTrainingModpack/releases/tag/beta) that are not in the stable release. 
* **Input Recording**: Trigger a recording and play it back (default binds: `R+DPad Down`, `R+DPad Up` respectively)! These recordings can be customized in terms of length between 60 and 600 frames, looping, and more! They can be configured to run in familiar situations like Mash or Ledge options and more - @GradualSyrup, @jugeeya
* * **Input Display**: (Not yet in beta) Show inputs in a per-status, frame counted log-style viewer! Choose between raw controller inputs and "Smash"-style inputs, being what the game actually understands and passes to fighters - @jugeeya, @xhudaman
* **Auto-Updater**: Allow the modpack …
=> Update beta changelog in preparation for 6.0 release

src/common/release.rs
Adds an informational dialog_ok() box if a user declines an update, letting them know that they can disable update checks in the modpack menu.
=> Add dialog_ok if the user declines the update

src/common/button_config.rs, src/common/menu.rs, src/training/input_record.rs, src/training/save_states.rs
In order to ensure users can't lock themselves out of the default menu combination (B+DPadUp), let's not use exclusive button combos anymore.
=> Don't Use Exclusive Button Combos

src/common/release.rs
The `is_older_than_current_version()` check improperly used a strict comparison, which led to a scenario where users would update then be prompted to update again, despite the successful application of the update.
=> Fix bug where auto-updater Would repeatedly prompt for updates

src/training/input_record.rs, src/training/mod.rs
Moves the function for incrementing frames and applying affects to a function that actually runs once per frame, and runs the checks symmetrically for both fighters. Fixes issues with initial short hops and hitstop messing up on recordings that most likely resulted from multiple command_flag_cat checks in the same frame.
=> Improve recording playback

src/common/consts.rs
Fixes issue where status names did not display for echoes because their statuses often use their parent characters' (Wolf included in that)
=> Fixes status names for echoes

src/common/mod.rs, src/training/mod.rs, src/training/ui/display.rs, src/training/ui/notifications.rs
Hides notifications when Combo Counter is off, since the notification is an expansion of the Combo Counter.
=> Hide Notifications when Combo Counter is Off

src/training/charge.rs
Levin will continue to be used for A button aerials after use until the bronze sword is used again - the last kind of aerial used now persists across save states.
=> Save Levin Aerial Usage

training_mod_consts/src/options.rs
When the "Playback Button Slots" setting had no slots selected, attempting to play back an input recording using the button combination would panic. By returning None instead, pressing the input playback button combination now does nothing instead of panicking.
=> Fix crash when playing back w/o playback slot selected

src/common/button_config.rs
Resolves #647 - if the vanilla menu or the modpack menu is up, then the other button combinations (e.g. load a save state or begin input recording) will no longer pass.
=> Prevent button combos from triggering while either menu is open

src/training/ui/display.rs
If the user turns off the combo counter in the vanilla menu, then we should hide the modpack notifications as well.
Huge props to @GradualSyrup for having already done the reverse engineering work to grab the setting from the vanilla menu!
=> Hide modpack notifications according to vanilla menu

src/training/buff.rs
When loading a save state with non-hero buffs selected in the menu, other unrelated spells (such as kaboom) would be cast instead. This PR fixes that bug by limiting the "buffs" that are applied to Hero to the correct ones.
=> Fix non-buff spells being applied to Hero upon Save State Load

src/common/release.rs, src/training/save_states.rs, src/training/ui/mod.rs, training_mod_consts/src/lib.rs, training_mod_consts/src/options.rs
No functional changes in this PR. I moved most of the code where we define the `Submenu` items out of macros and into a trait implementation. This should make it more straightforward for us to add new options to the menu if needed.
=> Make it more intuitive for devs to add new menu items

.github/workflows/rust.yml, Cargo.toml, src/lib.rs, src/training/ui/mod.rs
The GitHub Action for building the modpack is broken, and builds in other pull requests are currently failing as a consequence.
This PR includes the following:
* Replace deprecated GitHub Actions with newer versions
* Adds necessary feature flags to the project crate
* Removes deprecated name `default_features` and replace it with the now-preferred `default-features`
=> Update GitHub Actions workflow

.github/workflows/rust.yml
The `curl` command to download `libnro_hook.nro` and `libparam_hook.nro` did not include the necessary `--location` flag to follow redirects. This resulted in the creation of 0-byte files, instead of downloading the actual files located at the provided URLs.
This PR fixes the build to include the necessary `--location` flag.
=> Follow redirects in `curl` within GitHub Action

src/common/mod.rs
During Aegis downb, their position is considered to be (0,0) which could improperly trigger the distance-based mash triggers. This PR fixes that bug by returning `f32::MAX` as the distance during the swap.
=> Fix bug with Aegis swap improperly triggering on distance-based Mash Triggers

src/lib.rs
Stack size was too small on the auto-update thread, which caused the modpack to crash while installing OTA updates. Bumping up the stack size allows the updates to install successfully.
=> Fix broken auto-updates
