- source/main.c
- source/saltysd_helper.h
Don't you dare pull before testing <3
> Add training mode check

- src/common/consts.rs
- src/training/mash.rs
- src/training/shield.rs
Added forward/backwards roll options
See also:
https://github.com/jugeeya/TrainingModpackOverlay/pull/4
> Add Roll Options

- src/training/shield.rs
Fixed skipping the 4f additional shield hold
> Fix Grab OOS

- src/common/mod.rs
- src/lib.rs
- src/training/combo.rs
- src/training/mash.rs
- src/training/mod.rs
> Frame Advantage Refactor

- src/common/consts.rs
- src/common/mod.rs
- src/training/fast_fall.rs
- src/training/mod.rs
Spark effect is currently missing
> Add Fast Fall Toggle

- src/common/consts.rs
- src/training/combo.rs
- src/training/frame_counter.rs
- src/training/mod.rs
- Added frame counting logic to separate module.
- Added enum for fighter ids
> Add Frame Counter Module

- src/common/consts.rs
- src/common/mod.rs
- src/training/combo.rs
- src/training/frame_counter.rs
- src/training/ledge.rs
- src/training/mash.rs
- src/training/mod.rs
- src/training/save_states.rs
- src/training/shield.rs
- src/training/tech.rs
- Changed Mashing into a buffer system.
- Moved mash handling from shield module to mash module (except for Roll/Dodge)
- Allow more options OOS that require shield drop
> Refactor Mash Module

- src/common/consts.rs
- src/common/mod.rs
- src/hitbox_visualizer/mod.rs
- src/training/frame_counter.rs
- src/training/mash.rs
- src/training/mod.rs
- src/training/save_states.rs
- src/training/shield.rs
- src/training/tech.rs
Also fixed shield flash not dropping shield again
> Implement Tilts

- src/common/consts.rs
- src/common/mod.rs
- src/training/fast_fall.rs
- src/training/frame_counter.rs
- src/training/mash.rs
- src/training/mod.rs
- src/training/shield.rs
- Added option to delay the fast fall
-- useful to get timed aerials
- Fixed rising full hop aerials
> Add Fast Fall Frame Delay + OOS Reaction Frame Delay

- src/training/mash.rs
Fixed being a frame late
Flag is now immediately returned until the action is performed
Also restore Airdodge =>  Shield when grounded behavior
> Fix Mash Options

- src/training/mash.rs
Bowser uses a different status during upB for some reason
> Add Bowser UpB Workaround

- src/training/character_specific/bowser.rs
- src/training/character_specific/mod.rs
- src/training/fast_fall.rs
- src/training/mash.rs
- src/training/mod.rs
Added separate module for character specific handling
Updated fast fall check
Check against possible statuses instead of impossible ones
> Update Character Specifics / Fast Fall

- src/training/left_stick.rs
- src/training/mash.rs
Fixed buffering shield when being launched airborne while grounded.
> Fix Airdodge

- .gitmodules
- Cargo.toml
- src/common/consts.rs
- src/common/mod.rs
- src/lib.rs
- src/training/ledge.rs
- src/training/tech.rs
Tech options as a bitset instead of random/none/one
> Tech and Ledge options as bitflags

- src/training/mash.rs
- src/training/mod.rs
- src/training/shield.rs
> Revert To Command Flags

- src/common/consts.rs
- src/training/ledge.rs
- src/training/tech.rs
> Add  Bitflag Macro

- TrainingModpackOverlay/include/taunt_toggles.hpp
- TrainingModpackOverlay/source/gui_main.cpp
- src/common/consts.rs
- src/common/mod.rs
- src/training/directional_influence.rs
- src/training/fast_fall.rs
- src/training/full_hop.rs
- src/training/mash.rs
Fast Fall
Full Hop
Falling Aerial
> Apply Bit Flag

- TrainingModpackOverlay/Makefile
- src/training/mash.rs
- src/training/save_states.rs
Fixed air dodging when shield is buffered
Fixed followups not being cleared on reset (training mode/ save state/ tech)
Fixed resetting followups when landing normally after a mash toggle
> Mash Fixes

- src/training/mash.rs
Can just use the current buffer value
> Unnecessary global for aerial action buffer

- TrainingModpackOverlay/Makefile
- TrainingModpackOverlay/include/taunt_toggles.hpp
- TrainingModpackOverlay/source/gui_main.cpp
- src/common/consts.rs
- src/common/mod.rs
- src/training/ledge.rs
- src/training/mash.rs
- src/training/mod.rs
Add Ledge Delay Toggle
Add Aerial Delay Toggle
Increase Delay Values to 30
Add Dash Toggle
Version+
> Add Delay Options

- TrainingModpackOverlay/Makefile
- TrainingModpackOverlay/include/taunt_toggles.hpp
- TrainingModpackOverlay/source/gui_main.cpp
- src/common/consts.rs
- src/common/mod.rs
- src/hitbox_visualizer/mod.rs
- src/training/air_dodge_direction.rs
- src/training/combo.rs
- src/training/directional_influence.rs
- src/training/fast_fall.rs
- src/training/frame_counter.rs
- src/training/full_hop.rs
- src/training/ledge.rs
- src/training/mash.rs
- src/training/mod.rs
- src/training/reset.rs
- src/training/save_states.rs
- src/training/sdi.rs
- src/training/shield.rs
- src/training/shield_tilt.rs
- src/training/tech.rs
Renamed left_stick to air_dodge_direction
Added reset module
Moved training mode checks to skyline hooks
Added shield tilt toggle
> Shield Tilt & Refactor

- TrainingModpackOverlay/include/taunt_toggles.hpp
- TrainingModpackOverlay/source/gui_main.cpp
- src/common/consts.rs
- src/common/mod.rs
- src/hazard_manager/mod.rs
- src/lib.rs
Should work with all versions. No error popped up when loading with an 800 main but couldn't get past the main menu loading screen.
> Added stage hazard control

- src/training/shield.rs
Fixed the first hit not applying damage when  normal shield hold is selected
> Fix Shield: Hold

- TrainingModpackOverlay/include/taunt_toggles.hpp
- src/common/consts.rs
- src/training/shield.rs
Shield that takes damage normally, but doesn't decay over time
> Add Constant Shield Toggle

- TrainingModpackOverlay/include/taunt_toggles.hpp
- TrainingModpackOverlay/source/gui_main.cpp
- src/common/consts.rs
- src/common/mod.rs
- src/training/attack_angle.rs
- src/training/mash.rs
- src/training/mod.rs
Added toggle for chosing angled attacks
> Add Attack Angle

- TrainingModpackOverlay/include/taunt_toggles.hpp
- TrainingModpackOverlay/source/gui_main.cpp
- src/common/consts.rs
- src/common/mod.rs
- src/training/save_states.rs
Added toggle to not overwrite the damage when loading a save state
> Add Save State Damage Toggle

- TrainingModpackOverlay/include/taunt_toggles.hpp
- src/training/ledge.rs
- src/training/tech.rs
Support wall tech options
- Missed tech
- Tech jump (set to RollF for now)
> Wall Tech Options

- src/templates/menu.html
Arrange collapsed Lists in a grid.
Once expanded the list will take the full width
> 210416 grid layout

- src/templates/menu.html
- src/training/sdi.rs
Use descendant class selector instead of innerHTML
> Menu export bugfix

- src/common/menu.rs
- src/test.rs
- src/training/mod.rs
Change menu file name to avoid clashes with other programs which may write to `index.html`.
> Change menu file name to training_menu.html

- README.md
Adjust the wording in the readme and add a gif demonstrating the save state mirroring functionality
> Quick readme update

- src/common/consts.rs
- src/common/events.rs
- src/common/menu.rs
- src/common/mod.rs
- src/common/raygun_printer.rs
- src/common/release.rs
Probably going to do training module soonish too but I'm too tired right now
> Common module cleanup

- src/training/input_delay.rs
- src/training/mod.rs
Use NpadGcState instead of handheld state to save trigger info
> GCC Input Delay Fix

- src/training/ledge.rs
Makes CPUs properly buffer ledge options when no delay or 0 delay is selected. Allows users to practice trump setups that also cover buffered options.
> Ledge Trump Fix

- src/common/menu.rs
- src/lib.rs
> Quick Menu:  B Button hold fix, update from web menu

- src/common/menu.rs
- src/static/css/training_modpack.css
- src/templates/menu.html
* "Center" submenus within the tab container
* Avoid creating junk folders, since the htdocs dir already exists
> Menu fixes

- src/training/save_states.rs
Simple check before giving items
> Prevent Nana from Spawning with Items

- src/training/character_specific/items.rs
Diddy's Shield/Airdodge mash after state load needs to be fixed.
Robin's Book rotation needs fixing.
Need to deal with K Rool using his own crown and how it interacts with him (it disappears when near him, but doesn't get put on his head even if it is missing).
> Link and Diddy fixes, Players spawning with CPU item fixes

- src/templates/menu.html
Added onclick="closeOrExit()" to the top left back button to properly go back or exit using the touchscreen.
> Fix Touchscreen Back Button

- src/training/mash.rs
> Refine Mash Trigger Distances

- Cargo.toml
Upstream change for nn::tls connection context destructors
> Fix beta crashing after 8 event pushes

- src/lib.rs
- src/training/tech.rs
> Don't tech untechables

- README.md
A small update to the `README.md` file, to make it easier for first-time contributors to participate in Discord conversations.
> Add Discord hyperlinks to README.md

- .github/workflows/rust.yml
- README.md
We should update the beta changelog anytime we add a new feature or adjustment relevant to users.
> Add beta changelog to README

- src/training/ui/menu.rs
- Updated all TextBox member refs to remove `m_` prefix
- Refactored all references of shadow or text outline to use the new ui2d methods
- Added text outline and shadow hover/selected effects on all menu buttons
- Updated menu option buttons to center align label text
> Refactor menu for ui2d updates

- src/training/save_states.rs
> Fix PT load state freeze after L+R+A

- Cargo.toml
https://github.com/skyline-rs/rust-native-tls/pull/4
> Minreq/Native TLS: Ignore handshake failure

- README.md
- src/common/button_config.rs
- src/lib.rs
- src/training/save_states.rs
- training_mod_consts/src/lib.rs
Save State Save: Shield+DPad Down
Save State Load: Shield+DPad Up
Save State Next Slot: Grab+DPad Left
Save State Prev Slot: Grab+DPad Right
> Change default button config for save states: load/save to Shield, slots to Grab

- .github/workflows/rust.yml
- src/common/consts.rs
- src/common/dev_config.rs
- src/lib.rs
- src/training/attack_angle.rs
- src/training/charge.rs
- src/training/clatter.rs
- src/training/combo.rs
- src/training/crouch.rs
- src/training/directional_influence.rs
- src/training/frame_counter.rs
- src/training/ledge.rs
- src/training/mash.rs
- src/training/save_states.rs
- src/training/sdi.rs
- src/training/shield.rs
- src/training/shield_tilt.rs
- src/training/throw.rs
- src/training/ui/display.rs
- src/training/ui/notifications.rs
- training_mod_consts/src/options.rs
- training_mod_tui/src/list.rs
Minimal checker that just runs `cargo fmt --check` on all targets.
> Add rustfmt CI checker

- src/training/ui/menu.rs
- Added a fix to set `Icon` panes visiblility to `false` for the `MinButton` and `MaxButton` components on render
> Fixed bug where icons show on slider menu

- training_mod_consts/src/options.rs
Includes tumble as a default mash trigger
> Set tumble trigger as default

- src/training/input_record.rs
Fixes issues with holding a direction before recording starts causing issues on playback for tilts, as well as other conditions like pulling up Shulk's dial.
> Update standby function to use controller input

- src/training/input_record.rs
- training_mod_consts/src/lib.rs
- training_mod_consts/src/options.rs
Adds https://github.com/jugeeya/UltimateTrainingModpack/issues/547 .
> Add slots as menu options, randomize playback slots

- src/training/input_record.rs
Closes https://github.com/jugeeya/UltimateTrainingModpack/issues/550
> Input Recording Notifications

- .github/workflows/rust.yml
PR to clear out some of the Annotations on the GitHub Actions
> Update Github Actions

- src/training/input_record.rs
- src/training/ledge.rs
- src/training/mash.rs
- src/training/save_states.rs
- training_mod_consts/src/lib.rs
- training_mod_consts/src/options.rs
Closes https://github.com/jugeeya/UltimateTrainingModpack/issues/563
> Playback Slots for Actions and Ledge Options

- src/lib.rs
- src/training/buff.rs
- src/training/mash.rs
- src/training/mod.rs
- src/training/save_states.rs
Fixes #308. Fixes both visual and functional percentage issues with Wii Fit and Sephiroth's buffs. Wii Fit now has a hook that prevents her from being healed while she is buffing, and Sephiroth uses Sudden Death and Stamina mode flags to give himself Wing - looks like in that scenario the developers were having the same issue I was having with forcing Wing! Also removed some commented code that snuck in on an earlier PR.
> Buff Health Fixes

- src/training/save_states.rs
Prevent Aegis's sword from vanishing on state load
> Aegis sword article fix

- src/training/save_states.rs
- src/training/tech.rs
Fixes #556. Force Status Request change instead of requesting
> Fix Mistech Toggles for Jab Lock

- src/training/input_record.rs
- src/training/ledge.rs
- src/training/save_states.rs
- training_mod_consts/src/lib.rs
- training_mod_consts/src/options.rs
Just use button combination. Actually respect the config, too.
> Record Trigger Refactor

- src/common/menu.rs
- src/lib.rs
- Greatly improves responsiveness of menu
- Tried to have the functionality that holding an input for >= 20 frames but it just doesn't work lol
> Refactor Menu Input from Loop

- src/common/button_config.rs
- src/common/menu.rs
- src/training/mod.rs
- src/training/ui/menu.rs
- Reintroduce holding a direction for 20 frames to continue the input
- Make button combo inputs more consistent
> [Menu Input] Fixes to hold + consistency

- src/training/buff.rs
- src/training/combo.rs
- src/training/frame_counter.rs
- src/training/input_record.rs
- src/training/mod.rs
- src/training/ui/display.rs
- src/training/ui/notifications.rs
Matches the Lockout color with the color of the fighter, and ensures Playback stays up for as long as Playback continues
> Fully Match Input Recording Notifications with the Current state

- src/training/mod.rs
- src/training/save_states.rs
Fix save states having some inconsistency with the new input timing from button configuration changes
> Save state fix

- src/training/input_record.rs
- training_mod_consts/src/lib.rs
> Option to Crop Recording when it ends with neutral inputs

- src/common/menu.rs
- src/lib.rs
- src/training/ui/menu.rs
- training_mod_consts/src/lib.rs
- training_mod_consts/src/options.rs
- training_mod_tui/src/lib.rs
- training_mod_tui/src/main.rs
This refactor was with the intention of adding the ability to add dynamic text to our menus. Now, we can set the menu text to show the default input combination without having to hard-code what that combination actually is.
> Refactor string representation for buttons and menus

- src/common/release.rs
- src/training/save_states.rs
- training_mod_consts/src/options.rs
- training_mod_tui/src/main.rs
https://github.com/jugeeya/UltimateTrainingModpack/pull/592 accidentally pushed through changes that caused the enum names to be used rather than our handwritten ones.
> Fix Toggle Naming; Update import for skyline-web

- src/training/buff.rs
- src/training/mod.rs
Fixes occasional crash from incorrectly checking field of SoundModule instead of a module_accessor
> Fix PLAY_SE hook crash

- src/training/mod.rs
- training_mod_consts/src/lib.rs
- training_mod_consts/src/options.rs
> Stale dodge toggle

- src/common/mod.rs
- src/training/character_specific/kirby.rs
- src/training/charge.rs
- src/training/mod.rs
Save's Sora's current Spell in Save States.
Also applies to Kirby's Copy Ability.
More progress on #309.
> Save Sora Spell

- src/training/charge.rs
- src/training/save_states.rs
Adds Robin's Levin Sword and Tome charges to Save States, as well as the Levin Sword's recharge.
One left on #309!
> Robin Charges

- src/training/charge.rs
- src/training/mod.rs
Saves Incineroar's revenge power in Save States, and applies the correct effects.
This finishes off (the feasible parts) of #309!
> Save Incineroar Revenge Power

- src/training/buff.rs
- src/training/save_states.rs
- training_mod_consts/src/options.rs
Lets you easily switch between mini/half/full waft using the buff options menu.
> Add Wario waft options to buff menu

- README.md
- src/common/button_config.rs
- src/lib.rs
- training_mod_consts/src/lib.rs
- Press start now opens vanilla menu, hold opens mod menu
- immediately take input if holding for >= 10 frames
> [Menu Open] Switch hold vs press, immediately take input if holding for >= 10 frames

- Cargo.toml
- src/training/mod.rs
- src/training/save_states.rs
- training_mod_consts/src/lib.rs
- training_mod_consts/src/options.rs
Lets Random Slots be selectable, fixes a issue causing the ui setter function to run twice, and forces no optimization on non-release builds
> Save State Random Slots, other bugfixes

- src/lib.rs
- src/training/debug.rs
> Fix clippy warnings
